### ISSUE TITLE
Invalid resp3 type in async_receive

### ISSUE THREAD

**Issue by nejati-deriv** [boostorg/redis#44] opened 2023-01-18 19:09 UTC
You can use the following links to reproduce:
Receiver side: https://godbolt.org/z/TzM9T8P3x
Publisher side: https://godbolt.org/z/WaavdKGnc

Observations:
- If you run sender and receiver form one connection it doesn't happens.
- It seems the content of the published message is important (happens for some contents).

**Comment by mzimbres** [comment] 2023-01-18 20:49
I can reproduce.

**Comment by nejati-deriv** [comment] 2023-01-19 07:06
> I can reproduce, but only in release mode, not in debug.

It might be dependent to memory layout, I'm using clang-15 and it occurs in debug too.
Try another message that might happens in debug too.

**Comment by mzimbres** [comment] 2023-01-19 07:12
A subscriber implemented with low-level functions doesn't suffer from that problem, so it looks like it is not a parser problem. I it receives EOF from the server, perhaps for being able to keep-up with the high volume of messages, I have to measure more, see below

```cpp
#include <boost/asio.hpp>
#include <iostream>

#include <aedis.hpp>
#include <aedis/src.hpp>

namespace net = boost::asio;
namespace resp3 = aedis::resp3;
using resolver = net::use_awaitable_t<>::as_default_on_t<net::ip::tcp::resolver>;
using tcp_socket = net::use_awaitable_t<>::as_default_on_t<net::ip::tcp::socket>;
using aedis::adapter::adapt2;
using net::ip::tcp;

auto co_main(std::string host, std::string port) -> net::awaitable<void>
{
   try {
   auto ex = co_await net::this_coro::executor;

   resolver resv{ex};
   auto const addrs = co_await resv.async_resolve("127.0.0.1", "6379");
   tcp_socket socket{ex};
   co_await net::async_connect(socket, addrs);

   // Creates the request and writes to the socket.
   resp3::request req;
   req.push("HELLO", 3);
   req.push("SUBSCRIBE", "test-channel");
   co_await resp3::async_write(socket, req);

   std::string buffer, resp;

   auto dbuffer = net::dynamic_buffer(buffer);
   for (;;) {
      co_await resp3::async_read(socket, dbuffer);
      //std::cout << "ddd" << std::endl;
   }
   } catch(std::exception const& e) {
      std::cout << e.what() << std::endl;
   }
}

int main()
{
    net::io_context ioc{};
    net::co_spawn(ioc, co_main("127.0.0.1", "6379"), net::detached);
    ioc.run();
}

```

**Comment by mzimbres** [comment] 2023-01-28 08:49
Fixed in commit https://github.com/mzimbres/aedis/commit/56c0b280033886510e3f91f4704f4ed87da4a14d

**Closed** 2023-01-30 07:03 UTC
